import { BLOCK_TYPES, LIST_MARKERS, LIST_TYPES, ELEMENT_TYPES } from '../components/blocks';
import { IMAGE_LOADING } from '../components/blocks/image';
import { SECTION_TYPES } from '../components/sections';
import type { BeatSpotPageType } from '../types';
import { IMAGES } from './constants/images';

export const beatSpotPage: BeatSpotPageType = {
   heroSection: {
      id: 'beatspot-hero',
      type: SECTION_TYPES.HERO,
      classNames: ['beatspot-hero-section'],
      img: {
         id: 'beatspot-hero-image',
         alt: 'BeatSpot Hero Image',
         src: IMAGES.HERO_BEAT_SPOT_PAGE as ImageMetadata,
         classNames: ['beatspot-hero-image', 'w-full', 'h-full', 'object-cover'],
         loading: IMAGE_LOADING.EAGER,
      },
   },
   overviewSection: {
      id: 'beatspot-overview',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'mx-auto',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'overview-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Overview',
            level: 4,
         },
         {
            id: 'overview-block-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'BeatSpot is a self-initiated mobile app designed for hip-hop fans to discover, explore, and book tickets for upcoming hip-hop events based on their location and interests. This project focuses on designing a smooth, user-centered experience that simplifies event discovery and booking.',
         },
      ],
   },
   caseSection: {
      id: 'beatspot-case',
      classNames: [
         'w-full',
         'max-w-screen-xl',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'flex',
         'flex-col',
         'md:flex-row',
         'gap-6',
      ],
      elements: [
         {
            id: 'problem-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'problem-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Problem',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'problem-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'Hip-hop fans often struggle to discover relevant local events because event information is scattered across multiple platforms, and current apps mix different music genres, making search and discovery time-consuming and confusing.',
               },
            ],
         },
         {
            id: 'goal-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'goal-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Goal',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'goal-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'To create a seamless, user-friendly app that allows hip-hop fans to easily find, explore, and book tickets for events nearby, while providing a clear and engaging event discovery experience.',
               },
            ],
         },
         {
            id: 'role-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'role-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'My Role',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'role-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'This was an individual project where I planned and led each step of the design thinking process, applying my skills in mobile app UX/UI design.',
               },
            ],
         },
      ],
   },
   responsibilitiesSection: {
      id: 'beatspot-responsibilities',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'mx-auto',
      ],
      elements: [
         {
            id: 'responsibilities-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Responsibilities',
            level: 4,
         },
         {
            id: 'responsibilities-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Conducted user research and competitor research on event discovery and music apps to identify gaps and opportunities.',
               'Created user personas and journey maps to define user needs and guide design decisions.',
               'Designed low-fidelity wireframes, interactive prototypes, and high-fidelity UIs using Figma.',
               'Iteratively refined navigation and booking flows following usability best practices.',
               'Documented the full process in a case study format for portfolio presentation.',
            ],
         },
      ],
   },
   designThinkingSection: {
      id: 'beatspot-design-thinking',
      classNames: [
         'flex',
         'flex-col',
         'items-center',
         'pb-20',
         'w-full',
         'max-w-screen-lg',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'design-thinking-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Design Thinking Process',
            level: 4,
            classNames: ['mb-6'],
         },
         {
            id: 'design-thinking-paragraph',
            classNames: [
               'text-center',
               'w-full',
               'max-w-screen-md',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
            ],
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Design Thinking is a human-centered, iterative problem-solving approach that helps designers deeply understand users, define the right problems, and create innovative, user-focused solutions.',
         },
         {
            id: 'design-thinking-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotDesignThinking.svg',
            alt: 'Design Thinking Process Image',
            classNames: ['mt-8', 'w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   userResearchSection: {
      id: 'beatspot-user-research',
      classNames: [
         'flex',
         'flex-col',
         'pb-10',
         'space-y-6',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-research-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Research',
            level: 4,
            classNames: ['mb-6'],
         },
         {
            id: 'user-research-paragraph-1',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'To understand the needs, frustrations, and preferences of hip-hop fans, I conducted foundational research for BeatSpot. The goal was to gain insights into how users currently discover, explore, and book hip-hop events, and to identify pain points in existing event discovery platforms.',
         },
         {
            id: 'user-research-paragraph-2',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'I focused on qualitative research methods, combining:',
         },
         {
            id: 'user-research-methods-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Secondary research: analyzing competitor apps, websites, reviews, and reports to study existing solutions.',
               'Informal interviews: speaking with potential users to better understand their behaviors and expectations.',
            ],
         },
         {
            id: 'user-research-paragraph-3',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'These insights directly informed the design decisions and helped shape a user-centered experience.',
         },
      ],
   },
   userResearchKeyInsightsSection: {
      id: 'beatspot-user-research-key-insights',
      classNames: ['flex', 'flex-col', 'space-y-6'],
      elements: [
         {
            id: 'user-research-key-insights-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Research -  Key Insights',
            level: 4,
            classNames: ['w-full', 'max-w-screen-md', 'mx-auto', 'px-4', 'sm:px-8', 'md:px-12'],
         },
         {
            id: 'user-research-key-insights-cards',
            classNames: [
               'w-full',
               'max-w-screen-xl',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
               'mx-auto',
               'flex',
               'flex-col',
               'md:flex-row',
               'gap-6',
            ],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'user-research-key-insights-scattered-event-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'user-research-key-insights-scattered-event-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/beatSpotNumberOne.svg',
                        alt: 'Scattered Event Information',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Scattered Event Information',
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users struggle to find hip-hop events because listings are scattered across multiple platforms. (social media, ticketing websites, forums)',
                     },
                  ],
               },
               {
                  id: 'user-research-key-insights-complicated-booking-process-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'user-research-key-insights-complicated-booking-process-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/beatSpotNumberTwo.svg',
                        alt: 'Complicated Booking Process',
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Complicated Booking Process',
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users get frustrated because purchasing tickets often required multiple steps or redirections.',
                     },
                  ],
               },
               {
                  id: 'user-research-key-insights-limited-personalization-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'user-research-key-insights-limited-personalization-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/beatSpotNumberThree.svg',
                        alt: 'Limited Personalization & Recommendations',
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Limited Personalization & Recommendations',
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users struggle to find events based on their interests, location, or event type.',
                     },
                  ],
               },
               {
                  id: 'user-research-key-insights-limited-information-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'user-research-key-insights-limited-information-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/beatSpotNumberFour.svg',
                        alt: 'Limited Information Available',
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Limited Information Available',
                     },
                     {
                        id: 'user-research-key-insights-scattered-event-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users often get confused or frustrated when event cards and detail pages do not display key information.',
                     },
                  ],
               },
            ],
         },
      ],
   },
   personaSection: {
      id: 'beatspot-persona',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'persona-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Persona',
            level: 4,
         },
         {
            id: 'persona-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Based on the research insights, I developed a provisional persona to represent key user characteristics, goals, and behaviors. This persona helps guide design decisions and communicate user needs throughout the project.',
         },
         {
            id: 'persona-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotPersona.svg',
            alt: 'BeatSpot Persona Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   problemStatementSection: {
      id: 'beatspot-problem-statement',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'problem-statement-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Problem Statement',
            level: 4,
         },
         {
            id: 'problem-statement-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Zayn Arman is a busy marketing executive and hip-hop fan who needs a quick way to discover hip hop events nearby because he doesn’t have time to search across scattered platforms.',
         },
      ],
   },
   userJourneyMapSection: {
      id: 'beatspot-user-journey-map',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-journey-map-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Journey Map',
            level: 4,
         },
         {
            id: 'user-journey-map-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'By creating user journey map, I wanted to illustrate the process of how Zayn behaves, feels, and what they think while accomplishing their goals to address pain points or provide moments of delight.',
         },
         {
            id: 'user-journey-map-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotUserJourneyMap.svg',
            alt: 'BeatSpot User Journey Map Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   userFlowSection: {
      id: 'beatspot-user-flow',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-flow-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Flow',
            level: 4,
         },
         {
            id: 'user-flow-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The user flow outlines the journey from login to event discovery and ticket purchase. It helped ensure a seamless experience, minimizing friction and guiding users smoothly through each step of the app.',
         },
         {
            id: 'user-flow-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotUserFlow.svg',
            alt: 'BeatSpot User Flow Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   paperWireframesSection: {
      id: 'beatspot-paper-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'paper-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Paper Wireframes',
            level: 4,
         },
         {
            id: 'paper-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Focusing on the core features identified during user research, I sketched the first wireframes using pen and paper. ',
         },
         {
            id: 'paper-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotPaperWireframes.svg',
            alt: 'BeatSpot Paper Wireframes Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   digitalWireframesSection: {
      id: 'beatspot-digital-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'digital-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Digital Wireframes',
            level: 4,
         },
         {
            id: 'digital-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Building on the insights from research and paper sketches, I created digital wireframes in Figma to define the app’s layout and structure. These wireframes focused on the core user flows—event discovery, browsing details, and booking—while keeping navigation simple and intuitive.',
         },
         {
            id: 'digital-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotDigitalWireframe1.svg',
            alt: 'BeatSpot Digital Wireframes Image 1',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'digital-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotDigitalWireframe2.svg',
            alt: 'BeatSpot Digital Wireframes Image 2',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   lowFidelityPrototypeSection: {
      id: 'beatspot-low-fidelity-prototype',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'low-fidelity-prototype-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Low-Fidelity Prototype',
            level: 4,
         },
         {
            id: 'low-fidelity-prototype-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'I created a low-fidelity prototype from the user flow diagram and wireframes to test functionality before incorporating it into the final design and ensure accessibility for end-users.',
         },
         {
            id: 'low-fidelity-prototype-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotLowFidelityPrototype.svg',
            alt: 'BeatSpot Low-Fidelity Prototype Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   usabilityStudySection: {
      id: 'beatspot-usability-study',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'usability-study-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Usability Study',
            level: 4,
         },
         {
            id: 'usability-study-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'To validate the design and identify improvement opportunities, I conducted an unmoderated usability test with a small group of friends. Participants were asked to find an event, view its details, and proceed with booking.',
         },
      ],
   },
   usabilityStudyFindingsSection: {
      id: 'beatspot-usability-study-findings',
      classNames: ['flex', 'flex-col', 'space-y-6', 'pt-20'],
      elements: [
         {
            id: 'usability-study-findings-heading',
            classNames: ['w-full', 'max-w-screen-md', 'mx-auto', 'px-4', 'sm:px-8', 'md:px-12'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Usability Study - Findings',
            level: 4,
         },
         {
            id: 'usability-study-findings-cards',
            classNames: [
               'w-full',
               'max-w-screen-lg',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
               'flex',
               'flex-col',
               'md:flex-row',
               'gap-6',
            ],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'ticketing-flow-too-long-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'ticketing-flow-too-long-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/beatSpotNumberOne.svg',
                        alt: 'Ticketing Flow Too Long',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'ticketing-flow-too-long-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Ticketing Flow Too Long ',
                     },
                     {
                        id: 'ticketing-flow-too-long-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users felt that moving through separate ticket selection, order summary, and payment screens made the process lengthy.',
                     },
                  ],
               },
               {
                  id: 'uno-reminder-option-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'uno-reminder-option-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/beatSpotNumberTwo.svg',
                        alt: 'No Reminder Option in Favorites',
                     },
                     {
                        id: 'uno-reminder-option-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'No Reminder Option in Favorites',
                     },
                     {
                        id: 'uno-reminder-option-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: ' Users expected the ability to set reminders for events saved in their favorites, but the feature was missing.',
                     },
                  ],
               },
               {
                  id: 'event-details-lacked-map-integration-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'event-details-lacked-map-integration-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/beatSpotNumberThree.svg',
                        alt: 'Event Details Lacked Map Integration',
                     },
                     {
                        id: 'event-details-lacked-map-integration-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Event Details Lacked Map Integration',
                     },
                     {
                        id: 'event-details-lacked-map-integration-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users expected an embedded map to view and navigate to event locations directly within the app.',
                     },
                  ],
               },
            ],
         },
      ],
   },
   designRefinementsSection: {
      id: 'beatspot-design-refinements',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'design-refinements-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Design Refinements',
            level: 4,
         },
         {
            id: 'design-refinements-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Based on feedback:',
         },
         {
            id: 'design-refinements-list',
            classNames: ['pl-6'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.LIST,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Merged ticket selection and order summary into one screen for a faster flow.',
               'Added a reminder icon to favorite event cards.',
               'Added an interactive map to the event details page.',
            ],
         },
      ],
   },
   finalDesignSection: {
      id: 'beatspot-final-design',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-6',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'final-design-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Final Design',
            level: 4,
         },
         {
            id: 'final-design-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Below are the final high-fidelity screens of BeatSpot, refined based on user feedback to enhance usability and visual appeal, showcasing a seamless and engaging event discovery experience.',
         },
      ],
   },
   finalDesignImagesSection: {
      id: 'beatspot-final-design-images',
      classNames: [
         'grid',
         'grid-cols-1',
         'md:grid-cols-2',
         'lg:grid-cols-4',
         'gap-15',
         'w-full',
         'mx-auto',
         'py-15',
         'px-4',
         'sm:px-8',
         'md:px-40',
         'bg-neutral-900'
      ],
      elements: [
         {
            id: 'final-design-image-1',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign1.svg',
            alt: 'BeatSpot Final Design Image 1',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-2',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign2.svg',
            alt: 'BeatSpot Final Design Image 2',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-3',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign3.svg',
            alt: 'BeatSpot Final Design Image 3',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-4',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign4.svg',
            alt: 'BeatSpot Final Design Image 4',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-5',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign5.svg',
            alt: 'BeatSpot Final Design Image 5',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-6',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign6.svg',
            alt: 'BeatSpot Final Design Image 6',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-7',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign7.svg',
            alt: 'BeatSpot Final Design Image 7',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-8',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign8.svg',
            alt: 'BeatSpot Final Design Image 8',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-9',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign9.svg',
            alt: 'BeatSpot Final Design Image 9',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-10',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign10.svg',
            alt: 'BeatSpot Final Design Image 10',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-11',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign11.svg',
            alt: 'BeatSpot Final Design Image 11',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-image-12',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotFinalDesign12.svg',
            alt: 'BeatSpot Final Design Image 12',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   highFidelityPrototypeSection: {
      id: 'beatspot-high-fidelity-prototype',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-10',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'high-fidelity-prototype-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'High-Fidelity Prototype',
            level: 4,
         },
         {
            id: 'high-fidelity-prototype-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The final interactive prototype demonstrates how users seamlessly navigate through the app, showcasing refined interactions and a smooth end-to-end experience.',
         },
         {
            id: 'high-fidelity-prototype-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotHighFidelityPrototype.svg',
            alt: 'BeatSpot High-Fidelity Prototype Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   finalOutcomeAndLearningsSection: {
      id: 'beatspot-final-outcome-and-learnings',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'final-outcome-and-learnings-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Final Outcome and Learnings',
            level: 4,
         },
         {
            id: 'final-outcome-and-learnings-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Designing BeatSpot strengthened my skills in crafting intuitive event experiences. Through research, iteration, and testing, I created a user-friendly interface that makes event discovery and ticket purchasing',
         }
      ],
   },
   closingReflectionSection: {
      id: 'beatspot-closing-reflection',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'closing-reflection-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Closing Reflection',
            level: 4,
         },
         {
            id: 'closing-reflection-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'This project deepened my understanding of user-centered design and the importance of clarity in every interaction. It was a rewarding journey that refined both my creative and problem-solving skills.',
         },
      ],
   },
};
