import { LIST_MARKERS, LIST_TYPES, IMAGE_LOADING } from '../components/blocks';
import { BLOCK_TYPES, ELEMENT_TYPES } from '../components/utils';
import { SECTION_TYPES } from '../components/sections';
import type { FlixioPageType } from '../types';
import { IMAGES } from './constants/images';

export const flixioPage: FlixioPageType = {
   heroSection: {
      id: 'flixio-hero',
      type: SECTION_TYPES.HERO,
      classNames: ['pt-[80px]'],
      img: {
         id: 'flixio-hero-image',
         alt: 'Flixio Hero Image',
         src: IMAGES.HERO_FLIXIO_PAGE as ImageMetadata,
         classNames: ['w-full', 'h-auto', 'object-cover'],
         loading: IMAGE_LOADING.EAGER,
      },
   },
   overviewSection: {
      id: 'flixio-overview',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'mx-auto',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'overview-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Overview',
            level: 4,
         },
         {
            id: 'overview-block-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Flixio is a self-initiated cross-platform streaming app designed for mobile, tablet, and desktop. It delivers a seamless and cinematic viewing experience through responsive layouts, intuitive navigation, and a visually engaging interface across all devices.',
         },
      ],
   },
   caseSection: {
      id: 'flixio-case',
      classNames: [
         'w-full',
         'max-w-screen-xl',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'gap-6',
         'grid',
         'grid-cols-1',
         'md:grid-cols-3',
      ],
      elements: [
         {
            id: 'problem-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'problem-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Problem',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'problem-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'Users often experience cluttered layouts, inconsistent cross-device experiences, and complex navigation flows on streaming platforms, making content discovery and viewing less enjoyable.',
               },
            ],
         },
         {
            id: 'goal-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'goal-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Goal',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'goal-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'To design a responsive streaming experience that allows users to effortlessly discover, search, and watch content across devices.',
               },
            ],
         },
         {
            id: 'role-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'role-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'My Role',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'role-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'This was an individual project where I led every stage of the design thinking process — from research and wireframing to responsive design and interaction prototyping.',
               },
            ],
         },
      ],
   },
   responsibilitiesSection: {
      id: 'flixio-responsibilities',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'mx-auto',
      ],
      elements: [
         {
            id: 'responsibilities-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Responsibilities',
            level: 4,
         },
         {
            id: 'responsibilities-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Conducted competitor research to identify common streaming app patterns',
               'Created user personas and mapped user flows',
               'Designed wireframes, interactive prototypes, and high-fidelity UIs using Figma.',
               'Defined and refined navigation for a consistent cross-device experience',
               'Documented the design process with clear visuals for portfolio presentation',
            ],
         },
      ],
   },
   appPreviewSection: {
      id: 'flixio-app-preview',
      classNames: ['w-full', 'mx-auto'],
      elements: [
         {
            id: 'app-preview-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioPreview.svg',
            alt: 'Flixio App Preview',
            classNames: ['w-full', 'h-auto', 'object-cover'],
            loading: IMAGE_LOADING.LAZY,
         },
      ],
   },
   userResearchSection: {
      id: 'flixio-user-research',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'mx-auto',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-research-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Research',
            level: 4,
         },
         {
            id: 'user-research-block-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'To understand user expectations for streaming apps, I conducted:',
         },
         {
            id: 'user-research-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Secondary Research: Analyzed popular streaming platforms (Netflix, Disney+, and Prime Video) to study UI patterns, responsiveness, and content hierarchy.',
               'Informal Interviews: Asked participants about their viewing habits, frustrations, and preferred features across devices.',
            ],
         },
      ],
   },
   userResearchKeyInsightsSection: {
      id: 'flixio-user-research-key-insights',
      classNames: ['flex', 'flex-col', 'space-y-6'],
      elements: [
         {
            id: 'user-research-key-insights-block-heading',
            classNames: ['w-full', 'max-w-screen-md', 'mx-auto', 'px-4', 'sm:px-8', 'md:px-12'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Research -  Key Insights',
            level: 4,
         },
         {
            id: 'user-research-key-insights-cards',
            classNames: [
               'w-full',
               'max-w-screen-xl',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
               'gap-6',
               'grid',
               'grid-cols-1',
               'md:grid-cols-2',
               'lg:grid-cols-4',
            ],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'difficulty-finding-content-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'difficulty-finding-content-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/images/flixio/flixioNumberOne.svg',
                        alt: 'Difficulty Finding Content Quickly',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'difficulty-finding-content-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Difficulty Finding Content Quickly',
                     },
                     {
                        id: 'difficulty-finding-content-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users get overwhelmed by too much content and want faster, more personalized discovery.',
                     },
                  ],
               },
               {
                  id: 'seamless-cross-device-experience-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'seamless-cross-device-experience-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/images/flixio/flixioNumberTwo.svg',
                        alt: 'Seamless Cross-Device Experience',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'seamless-cross-device-experience-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Seamless Cross-Device Experience',
                     },
                     {
                        id: 'seamless-cross-device-experience-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'They expect to switch between devices smoothly without losing progress or consistency.',
                     },
                  ],
               },
               {
                  id: 'cluttered-interfaces-cause-confusion-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'cluttered-interfaces-cause-confusion-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/images/flixio/flixioNumberThree.svg',
                        alt: 'Cluttered Interfaces Cause Confusion',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'cluttered-interfaces-cause-confusion-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Cluttered Interfaces Cause Confusion',
                     },
                     {
                        id: 'cluttered-interfaces-cause-confusion-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Overloaded screens make navigation hard; users prefer clean, focused layouts.',
                     },
                  ],
               },
               {
                  id: 'personalized-suggestions-boost-enjoyment-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'personalized-suggestions-boost-enjoyment-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/images/flixio/flixioNumberFour.svg',
                        alt: 'Personalized Suggestions Boost Enjoyment',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'personalized-suggestions-boost-enjoyment-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Personalized Suggestions Boost Enjoyment',
                     },
                     {
                        id: 'personalized-suggestions-boost-enjoyment-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Tailored recommendations and easy access to favorites make the experience engaging.',
                     },
                  ],
               },
            ],
         },
      ],
   },
   personaSection: {
      id: 'flixio-persona',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'persona-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Persona',
            level: 4,
         },
         {
            id: 'persona-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'After analyzing the key findings, I created a provisional persona to help communicate information collected about users through out the design process.',
         },
         {
            id: 'persona-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioPersona.svg',
            alt: 'Flixio Persona Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   problemStatementSection: {
      id: 'flixio-problem-statement',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'problem-statement-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Problem Statement',
            level: 4,
         },
         {
            id: 'problem-statement-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Ryan is a busy professional who needs an organized, personalized streaming platform because he wants to quickly discover and watch content without spending time on unnecessary browsing.',
         },
      ],
   },
   userFlowSection: {
      id: 'flixio-user-flow',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-flow-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Flow',
            level: 4,
         },
         {
            id: 'user-flow-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The user flow illustrates the step-by-step journey users take on Flixio — from logging in to discovering, viewing, and continuing content. Mapping this flow helped identify key interactions, simplify navigation, and ensure a seamless streaming experience across mobile, tablet, and desktop.',
         },
         {
            id: 'user-flow-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioUserFlow.svg',
            alt: 'Flixio User Flow Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   paperWireframesSection: {
      id: 'flixio-paper-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'paper-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Paper Wireframes',
            level: 4,
         },
         {
            id: 'paper-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Focusing on the core features identified during user research, I sketched the first wireframes using pen and paper.',
         },
         {
            id: 'paper-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/beatSpotPaperWireframes.svg',
            alt: 'Flixio Paper Wireframes Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   digitalWireframesSection: {
      id: 'flixio-digital-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'digital-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Digital Wireframes',
            level: 4,
         },
         {
            id: 'digital-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Based on research insights and initial sketches, I created digital wireframes in Figma to define Flixio’s layout and structure. The wireframes focused on core flows—content discovery, search, and watching—while maintaining a clean and consistent navigation across devices.',
         },
         {
            id: 'digital-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioDigitalWireframe1.svg',
            alt: 'Flixio Digital Wireframes Image 1',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'digital-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioDigitalWireframe2.svg',
            alt: 'Flixio Digital Wireframes Image 2',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   lowFidelityPrototypeSection: {
      id: 'flixio-low-fidelity-prototype',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'low-fidelity-prototype-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Low-Fidelity Prototype',
            level: 4,
         },
         {
            id: 'low-fidelity-prototype-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'I created a low-fidelity prototype from the user flow diagram and wireframes to test functionality before incorporating it into the final design and ensure accessibility for end-users.',
         },
         {
            id: 'low-fidelity-prototype-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioLowFidelityPrototype.svg',
            alt: 'Flixio Low-Fidelity Prototype Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   finalDesignSection: {
      id: 'flixio-final-design',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-6',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'final-design-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Final Design',
            level: 4,
         },
      ],
   },
   finalDesignMobileImagesSection: {
      id: 'flixio-final-design-mobile-images',
      classNames: [
         'grid',
         'grid-cols-1',
         'md:grid-cols-2',
         'lg:grid-cols-4',
         'gap-15',
         'w-full',
         'mx-auto',
         'py-10',
         'mt-8',
         'px-4',
         'sm:px-8',
         'md:px-40',
         'bg-neutral-900',
      ],
      elements: [
         {
            id: 'final-design-mobile-image-1',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignMobile1.svg',
            alt: 'Flixio Final Design Mobile Image 1',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-mobile-image-2',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignMobile2.svg',
            alt: 'Flixio Final Design Mobile Image 2',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-mobile-image-3',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignMobile3.svg',
            alt: 'Flixio Final Design Mobile Image 3',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-mobile-image-4',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignMobile4.svg',
            alt: 'Flixio Final Design Mobile Image 4',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   finalDesignTabImagesSection: {
      id: 'flixio-final-design-tab-images',
      classNames: [
         'grid',
         'grid-cols-1',
         'md:grid-cols-2',
         'lg:grid-cols-4',
         'gap-7',
         'w-full',
         'mx-auto',
         'py-15',
         'mt-20',
         'px-4',
         'sm:px-8',
         'md:px-40',
         'bg-neutral-900',
      ],
      elements: [
         {
            id: 'final-design-tab-image-1',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignTabImage1.svg',
            alt: 'Flixio Final Design Tab Image 1',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-tab-image-2',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignTabImage2.svg',
            alt: 'Flixio Final Design Tab Image 2',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-tab-image-3',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignTabImage3.svg',
            alt: 'Flixio Final Design Tab Image 3',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-tab-image-4',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignTabImage4.svg',
            alt: 'Flixio Final Design Tab Image 4',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   finalDesignDesktopImagesSection: {
      id: 'flixio-final-design-desktop-images',
      classNames: [
         'grid',
         'grid-cols-1',
         'md:grid-cols-2',
         'lg:grid-cols-2',
         'gap-10',
         'w-full',
         'mx-auto',
         'py-20',
         'mt-20',
         'px-4',
         'sm:px-8',
         'md:px-40',
         'bg-neutral-900',
      ],
      elements: [
         {
            id: 'final-design-desktop-image-1',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignDesktopImage1.svg',
            alt: 'Flixio Final Design Desktop Image 1',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-desktop-image-2',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignDesktopImage2.svg',
            alt: 'Flixio Final Design Desktop Image 2',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-desktop-image-3',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignDesktopImage3.svg',
            alt: 'Flixio Final Design Desktop Image 3',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'final-design-desktop-image-4',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/flixioFinalDesignDesktopImage4.svg',
            alt: 'Flixio Final Design Desktop Image 4',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   highFidelityPrototypeSection: {
      id: 'flixio-high-fidelity-prototype',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'high-fidelity-prototype-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'High-Fidelity Prototype',
            level: 4,
         },
         {
            id: 'high-fidelity-prototype-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The high-fidelity prototype showcases the final visual design and interactions, allowing users to experience Flixio as a fully functional streaming platform with real content and seamless navigation.',
         },
         {
            id: 'high-fidelity-prototype-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/images/flixio/beatSpotHighFidelityPrototype.svg',
            alt: 'Flixio High-Fidelity Prototype Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   finalOutcomeAndLearningsSection: {
      id: 'flixio-final-outcome-and-learnings',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'final-outcome-and-learnings-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Final Outcome and Learnings',
            level: 4,
         },
         {
            id: 'final-outcome-and-learnings-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Designing Flixio was an exciting journey in creating a seamless and engaging streaming experience. The process enhanced my skills in cross-platform and adaptive design, content hierarchy, and crafting intuitive user flows that simplify content discovery.',
         },
      ],
   },
   closingReflectionSection: {
      id: 'beatspot-closing-reflection',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'closing-reflection-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Closing Reflection',
            level: 4,
         },
         {
            id: 'closing-reflection-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Flixio allowed me to explore the full design process of a multi-platform app. Through research and iteration, I learned how small refinements can elevate usability and consistency, resulting in a cinematic and user-friendly experience across all devices.',
         },
      ],
   },
};
