import { IMAGE_LOADING, LIST_MARKERS, LIST_TYPES } from '../components/blocks';
import { SECTION_TYPES } from '../components/sections';
import { BLOCK_TYPES, ELEMENT_TYPES } from '../components/utils';
import type { LoginFlowPageType } from '../types';
import { IMAGES } from './constants/images';

export const loginFlowPage: LoginFlowPageType = {
   heroSection: {
      id: 'loginFlow-hero',
      type: SECTION_TYPES.HERO,
      classNames: ['loginFlow-hero-section'],
      img: {
         id: 'loginFlow-hero-image',
         alt: 'LoginFlow Hero Image',
         src: IMAGES.HERO_LOGIN_FLOW_PAGE as ImageMetadata,
         classNames: ['loginFlow-hero-image', 'w-full', 'h-full', 'object-cover'],
         loading: IMAGE_LOADING.EAGER,
      },
   },
   overviewSection: {
      id: 'loginFlow-overview',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-20',
         'mx-auto',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'overview-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Overview',
            level: 4,
         },
         {
            id: 'overview-block-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'This project is an extension of BeatSpot – Hip Hop Event Finder App, created to showcase the complete login flow. It focuses on designing a cohesive entry experience for users, covering onboarding, sign-in, sign-up, and password recovery.',
         },
      ],
   },
   caseSection: {
      id: 'loginFlow-case',
      classNames: [
         'w-full',
         'max-w-screen-xl',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'flex',
         'flex-col',
         'md:flex-row',
         'gap-6',
      ],
      elements: [
         {
            id: 'problem-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'problem-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Problem',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'problem-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'Insert one to two sentences about the problem(s) you were trying to solve.',
               },
            ],
         },
         {
            id: 'goal-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'goal-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Goal',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'goal-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'To design a simple, accessible, and efficient login flow that builds user trust and ensures a smooth first-time experience.',
               },
            ],
         },
         {
            id: 'role-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'role-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'My Role',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'role-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'As the sole designer, I planned and executed the entire process — from mapping user flow and wireframing to creating high-fidelity mockups.',
               },
            ],
         },
      ],
   },
   responsibilitiesSection: {
      id: 'loginFlow-responsibilities',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'mx-auto',
      ],
      elements: [
         {
            id: 'responsibilities-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Responsibilities',
            level: 4,
         },
         {
            id: 'responsibilities-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Researched common login and authentication patterns across popular apps.',
               'Defined the complete user flow for onboarding, sign-in, sign-up, and password recovery.',
               'Designed low-fidelity wireframes and interactive high-fidelity prototypes in Figma.',
               'Ensured visual and functional consistency with the main BeatSpot app design system.',
            ],
         },
      ],
   },
   userFlowSection: {
      id: 'login-flow-user-flow',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-flow-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Flow',
            level: 4,
         },
         {
            id: 'user-flow-paragraph1',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The user flow illustrates the complete login journey in BeatSpot — covering multiple scenarios such as:',
         },
         {
            id: 'user-flow-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'First-time user registration',
               'Returning users signing in',
               'Users recovering forgotten password',
            ],
         },
         {
            id: 'user-flow-paragraph2',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Mapping these flows helped ensure a smooth, intuitive authentication experience',
         },
         {
            id: 'user-flow-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/loginFlowUserFlow.svg',
            alt: 'Login Flow User Flow Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   paperWireframesSection: {
      id: 'login-flow-paper-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'paper-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Paper Wireframes',
            level: 4,
         },
         {
            id: 'paper-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Focusing on the core features identified during user research, I sketched the first wireframes using pen and paper.',
         },
         {
            id: 'paper-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotPaperWireframes.svg',
            alt: 'Login Flow Paper Wireframes Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   digitalWireframesSection: {
      id: 'login-flow-digital-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'digital-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Digital Wireframes',
            level: 4,
         },
         {
            id: 'digital-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Based on research insights and user flow mapping, I created digital wireframes in Figma to outline BeatSpot’s login flow.',
         },
         {
            id: 'digital-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/loginFlowDigitalWireframe.svg',
            alt: 'Login Flow Digital Wireframes Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   highFidelityDesignSection: {
      id: 'login-flow-high-fidelity-design',
      classNames: ['flex', 'flex-col', 'space-y-10', 'pt-20'],
      elements: [
         {
            id: 'high-fidelity-design-section1',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'flex',
               'flex-col',
               'space-y-6',
               'w-full',
               'max-w-screen-md',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'High-Fidelity Design',
                  level: 4,
               },
               {
                  id: 'high-fidelity-design-paragraph1',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: '**Splash Screen** – Features the BeatSpot logo on a bold, energetic background that captures the rhythm and vibe of hip-hop culture.',
               },
               {
                  id: 'high-fidelity-design-paragraph2',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: '**Onboarding Screens** – Swipable screens introduce key app features with minimal text and clear visuals, guiding users smoothly through the app’s value.',
               },
               {
                  id: 'high-fidelity-design-paragraph3',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: '**Welcome Screen** – A simple, inviting layout showcasing the logo and clear calls-to-action for Sign In and Sign Up.',
               },
            ],
         },
         {
            id: 'high-fidelity-design-section2',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'grid',
               'grid-cols-1',
               'md:grid-cols-2',
               'lg:grid-cols-4',
               'gap-15',
               'w-full',
               'mx-auto',
               'py-10',
               'px-4',
               'sm:px-8',
               'md:px-40',
               'bg-neutral-900',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-image-1',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign1.svg',
                  alt: 'Login Flow Final Design Image 1',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-2',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign2.svg',
                  alt: 'Login Flow Final Design Image 2',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-3',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign3.svg',
                  alt: 'Login Flow Final Design Image 3',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-4',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign4.svg',
                  alt: 'Login Flow Final Design Image 4',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
            ],
         },
         {
            id: 'high-fidelity-design-section3',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'flex',
               'flex-col',
               'space-y-6',
               'w-full',
               'max-w-screen-md',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-paragraph4',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: '**Sign In Screen** – Clean and intuitive login form with a primary Sign In button and social login options via Facebook, Google, and Apple for convenience.',
               },
               {
                  id: 'high-fidelity-design-paragraph5',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: '**Sign Up Screen** – Straightforward registration form with clear input fields, prominent primary button button, and quick access to social signup options.',
               },
            ],
         },
         {
            id: 'high-fidelity-design-section4',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'grid',
               'grid-cols-1',
               'md:grid-cols-2',
               'lg:grid-cols-4',
               'gap-15',
               'w-full',
               'mx-auto',
               'py-10',
               'px-4',
               'sm:px-8',
               'md:px-40',
               'bg-neutral-900',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-image-5',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign5.svg',
                  alt: 'Login Flow Final Design Image 5',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-6',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign6.svg',
                  alt: 'Login Flow Final Design Image 6',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-7',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign7.svg',
                  alt: 'Login Flow Final Design Image 7',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-8',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign8.svg',
                  alt: 'Login Flow Final Design Image 8',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
            ],
         },
         {
            id: 'high-fidelity-design-section5',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'flex',
               'flex-col',
               'space-y-6',
               'w-full',
               'max-w-screen-md',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-paragraph6',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: '**Forgot Password** – A smooth, three-step recovery process with clear screens for password reset request, new password setup, and confirmation.',
               },
            ],
         },
         {
            id: 'high-fidelity-design-section6',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'grid',
               'grid-cols-1',
               'md:grid-cols-2',
               'lg:grid-cols-4',
               'justify-items-center',
               'gap-15',
               'w-full',
               'mx-auto',
               'py-10',
               'px-4',
               'sm:px-8',
               'md:px-40',
               'bg-neutral-900',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-image-5',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign5.svg',
                  alt: 'Login Flow Final Design Image 5',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-9',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign9.svg',
                  alt: 'Login Flow Final Design Image 9',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-10',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign10.svg',
                  alt: 'Login Flow Final Design Image 10',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-11',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign11.svg',
                  alt: 'Login Flow Final Design Image 11',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
            ],
         },
         {
            id: 'high-fidelity-design-section7',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'flex',
               'flex-col',
               'space-y-6',
               'w-full',
               'max-w-screen-md',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-paragraph7',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: '**Error States** – Thoughtfully designed error messages and highlights to provide clear feedback and help users correct issues quickly.',
               },
            ],
         },
         {
            id: 'high-fidelity-design-section8',
            elementType: ELEMENT_TYPES.CONTAINER,
            classNames: [
               'grid',
               'grid-cols-1',
               'md:grid-cols-2',
               'lg:grid-cols-4',
               'justify-items-center',
               'gap-15',
               'w-full',
               'mx-auto',
               'py-10',
               'px-4',
               'sm:px-8',
               'md:px-40',
               'bg-neutral-900',
            ],
            elements: [
               {
                  id: 'high-fidelity-design-image-12',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign12.svg',
                  alt: 'Login Flow Final Design Image 12',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-13',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign13.svg',
                  alt: 'Login Flow Final Design Image 13',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-14',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign15.svg',
                  alt: 'Login Flow Final Design Image 15',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'high-fidelity-design-image-14',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/loginFlowFinalDesign14.svg',
                  alt: 'Login Flow Final Design Image 14',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
            ],
         },
      ],
   },
   finalOutcomeAndLearningsSection: {
      id: 'login-flow-final-outcome-and-learnings',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'final-outcome-and-learnings-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Final Outcome and Learnings',
            level: 4,
         },
         {
            id: 'final-outcome-and-learnings-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Designing the BeatSpot login flow helped me craft a seamless and visually engaging authentication experience. I refined my understanding of user flows, accessibility, and error handling while keeping the brand’s hip-hop energy alive through consistent visuals.',
         },
      ],
   },
   closingReflectionSection: {
      id: 'login-flow-closing-reflection',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-20',
         'pb-25',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'closing-reflection-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Closing Reflection',
            level: 4,
         },
         {
            id: 'closing-reflection-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'This project strengthened my skills in creating clear, user-friendly login experiences. I learned the importance of balancing creativity with usability and ensuring every interaction feels smooth and intuitive.',
         },
      ],
   },
};
