import { IMAGE_LOADING, BUTTON_VARIANTS } from '../components/blocks';
import { SECTION_TYPES } from '../components/sections';
import { BLOCK_TYPES, ELEMENT_TYPES } from '../components/utils';
import type { ProjectsPageType } from '../types';
import { IMAGES } from './constants/images';

export const projectsPage: ProjectsPageType = {
   heroSection: {
      id: 'projects-hero-section',
      type: SECTION_TYPES.HERO,
      classNames: ['py-12'],
      img: {
         id: 'projects-hero-image',
         src: IMAGES.HERO_PROJECTS_PAGE as ImageMetadata,
         alt: 'Hero',
         classNames: ['absolute', 'top-0', 'right-0', 'z-0'],
         loading: IMAGE_LOADING.EAGER,
      },
   },
   projectsSection: {
      id: 'projects-section',
      classNames: ['projects-section'],
      elements: [
         {
            id: 'heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Projects',
            level: 2,
            classNames: ['projects-heading', 'mb-4'],
         },
         {
            id: 'beat-spot-media-card',
            classNames: [
               'grid grid-cols-1 md:grid-cols-2',
               'shadow-[0_6px_64px_0_rgba(112,144,176,0.1)]',
               'rounded-3xl',
               'overflow-hidden',
               'bg-neutral-900',
            ],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.MEDIA_CARD,
            image: {
               id: 'beat-spot-media-card-image',
               type: BLOCK_TYPES.IMAGE,
               src: '/images/beat-spot/beatSpotMediaCard.svg',
               alt: 'Beat Spot Media Card',
               position: 'right',
               classNames: ['w-full', 'h-full', 'object-cover'],
            },
            containers: [
               {
                  id: 'beat-spot-title-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'items-center',
                     'justify-center',
                     'p-12',
                     'space-y-6',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'beat-spot-title',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.HEADING,
                        text: 'BeatSpot',
                        level: 3,
                     },
                     {
                        id: 'beat-spot-description',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.PARAGRAPH,
                        text: 'BeatSpot is a mobile app that makes it easy for users to discover, explore, and book nearby hip hop concerts, battles, and festivals.',
                        classNames: ['text-neutral-400'],
                     },
                     {
                        id: 'beat-spot-cta-button',
                        classNames: ['rounded-full', 'w-fit'],
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.BUTTON,
                        variant: BUTTON_VARIANTS.SECONDARY,
                        href: {
                           id: 'beat-spot-link',
                           url: '/projects/beatspot',
                           label: 'View Project',
                        },
                     },
                  ],
               },
            ],
         },
         {
            id: 'sun-ray-media-card',
            classNames: [
               'grid grid-cols-1 md:grid-cols-2',
               'shadow-[0_6px_64px_0_rgba(112,144,176,0.1)]',
               'rounded-3xl',
               'overflow-hidden',
               // 'md:h-[524px]',
               'bg-neutral-900',
            ],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.MEDIA_CARD,
            image: {
               id: 'sun-ray-media-card-image',
               type: BLOCK_TYPES.IMAGE,
               src: '/images/sun-ray/sunRayMediaCard.svg',
               alt: 'Sun Ray Media Card',
               position: 'left',
               classNames: ['w-full', 'h-full', 'object-cover'],
            },
            containers: [
               {
                  id: 'sun-ray-title',
                  elementType: ELEMENT_TYPES.CONTAINER,
                  classNames: [
                     'flex',
                     'flex-col',
                     'items-center',
                     'justify-center',
                     'p-12',
                     'space-y-6',
                  ],
                  elements: [
                     {
                        id: 'sun-ray-title',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.HEADING,
                        text: 'SunRay',
                        level: 3,
                     },
                     {
                        id: 'sun-ray-description',
                        classNames: ['text-neutral-400'],
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.PARAGRAPH,
                        text: 'SunRay is a responsive e-commerce website for a sunglass store, designed with a clean UI and seamless shopping experience across desktop and mobile.',
                     },
                     {
                        id: 'sun-ray-cta-button',
                        classNames: ['rounded-full', 'w-fit'],
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.BUTTON,
                        variant: BUTTON_VARIANTS.SECONDARY,
                        href: {
                           id: 'sun-ray-link',
                           url: '/projects/sunray',
                           label: 'View Project',
                        },
                     },
                  ],
               },
            ],
         },
         {
            id: 'flixio-media-card',
            classNames: [
               'grid grid-cols-1 md:grid-cols-2',
               'shadow-[0_6px_64px_0_rgba(112,144,176,0.1)]',
               'rounded-3xl',
               'overflow-hidden',
               // 'md:h-[524px]',
               'bg-neutral-900',
            ],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.MEDIA_CARD,
            image: {
               id: 'flixio-media-card-image',
               type: BLOCK_TYPES.IMAGE,
               src: '/images/flixio/flixioMediaCard.svg',
               alt: 'Flixio Media Card',
               position: 'right',
               classNames: ['w-full', 'h-full', 'object-cover'],
            },
            containers: [
               {
                  id: 'flixio-title-container',
                  elementType: ELEMENT_TYPES.CONTAINER,
                  classNames: [
                     'flex',
                     'flex-col',
                     'items-center',
                     'justify-center',
                     'p-12',
                     'space-y-6',
                  ],
                  elements: [
                     {
                        id: 'flixio-title',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.HEADING,
                        text: 'Flixio',
                        level: 3,
                     },
                     {
                        id: 'flixio-description',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.PARAGRAPH,
                        text: 'Flixio is a cross-platform streaming application designed for mobile, tablet, and desktop, allowing users to discover, search, and enjoy movies and series seamlessly across devices.',
                        classNames: ['text-neutral-400'],
                     },
                     {
                        id: 'flixio-cta-button',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.BUTTON,
                        variant: BUTTON_VARIANTS.SECONDARY,
                        href: {
                           id: 'flixio-website-link',
                           url: '/projects/flixio',
                           label: 'View Project',
                        },
                        classNames: ['rounded-full', 'w-fit'],
                     },
                  ],
               },
            ],
         },
         {
            id: 'login-flow-media-card',
            classNames: [
               'grid grid-cols-1 md:grid-cols-2',
               'shadow-[0_6px_64px_0_rgba(112,144,176,0.1)]',
               'rounded-3xl',
               'overflow-hidden',
               'bg-neutral-900',
            ],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.MEDIA_CARD,
            image: {
               id: 'login-flow-media-card-image',
               type: BLOCK_TYPES.IMAGE,
               src: '/images/login-flow/loginFlowMediaCard.svg',
               alt: 'Login Flow Media Card',
               position: 'left',
               classNames: ['w-full', 'h-full', 'object-cover'],
            },
            containers: [
               {
                  id: 'login-flow-title-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'items-center',
                     'justify-center',
                     'p-12',
                     'space-y-6',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'login-flow-title',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.HEADING,
                        text: 'Login Flow',
                        level: 3,
                     },
                     {
                        id: 'login-flow-description',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.PARAGRAPH,
                        text: 'A complete mobile authentication flow for BeatSpot, featuring onboarding, sign in/up, password recovery, and error handling—designed for a seamless user experience.',
                        classNames: ['text-neutral-400'],
                     },
                     {
                        id: 'login-flow-cta-button',
                        classNames: ['rounded-full', 'w-fit'],
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.BUTTON,
                        variant: BUTTON_VARIANTS.SECONDARY,
                        href: {
                           id: 'login-flow-link',
                           url: '/projects/login-flow',
                           label: 'View Project',
                        },
                     },
                  ],
               },
            ],
         },
         {
            id: 'portfolio-media-card',
            classNames: [
               'grid grid-cols-1 md:grid-cols-2',
               'shadow-[0_6px_64px_0_rgba(112,144,176,0.1)]',
               'rounded-3xl',
               'overflow-hidden',
               'bg-neutral-900',
            ],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.MEDIA_CARD,
            image: {
               id: 'portfolio-media-card-image',
               type: BLOCK_TYPES.IMAGE,
               src: '/images/portfolio/portfolioMediaCard.svg',
               alt: 'Portfolio Media Card',
               position: 'right',
               classNames: ['w-full', 'h-full', 'object-cover'],
            },
            containers: [
               {
                  id: 'portfolio-title-container',
                  elementType: ELEMENT_TYPES.CONTAINER,
                  classNames: [
                     'flex',
                     'flex-col',
                     'items-center',
                     'justify-center',
                     'p-12',
                     'space-y-6',
                  ],
                  elements: [
                     {
                        id: 'portfolio-title',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.HEADING,
                        text: 'Portfolio Website',
                        level: 3,
                     },
                     {
                        id: 'portfolio-description',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.PARAGRAPH,
                        text: 'A personal portfolio website project for web, showcasing UI/UX design and frontend development skills, built for desktop and mobile experiences.',
                        classNames: ['text-neutral-400'],
                     },
                     {
                        id: 'portfolio-cta-button',
                        classNames: ['rounded-full', 'w-fit'],
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.BUTTON,
                        variant: BUTTON_VARIANTS.SECONDARY,
                        href: {
                           id: 'portfolio-link',
                           url: '/projects/portfolio',
                           label: 'View Project',
                        },
                     },
                  ],
               },
            ],
         },
      ],
   },
} as const;
