import { IMAGE_LOADING, LIST_MARKERS, LIST_TYPES } from '../components/blocks';
import { SECTION_TYPES } from '../components/sections';
import { BLOCK_TYPES, ELEMENT_TYPES } from '../components/utils';
import type { SunRayPageType } from '../types';
import { IMAGES } from './constants/images';

export const sunRayPage: SunRayPageType = {
   heroSection: {
      id: 'sunray-hero',
      type: SECTION_TYPES.HERO,
      classNames: ['sunray-hero-section'],
      img: {
         id: 'sunray-hero-image',
         alt: 'SunRay Hero Image',
         src: IMAGES.HERO_SUN_RAY_PAGE as ImageMetadata,
         classNames: ['sunray-hero-image', 'w-full', 'h-full', 'object-cover'],
         loading: IMAGE_LOADING.EAGER,
      },
   },
   overviewSection: {
      id: 'sunray-overview',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'mx-auto',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'overview-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Overview',
            level: 4,
         },
         {
            id: 'overview-block-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'SunRays is a self-initiated project focused on designing a modern, responsive e-commerce website for a sunglass store. The website is designed for both desktop and mobile, ensuring a seamless shopping experience across devices.',
         },
      ],
   },
   caseSection: {
      id: 'sunray-case',
      classNames: [
         'w-full',
         'max-w-screen-xl',
         'mx-auto',
         'mt-20',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'gap-6',
         'grid',
         'grid-cols-1',
         'md:grid-cols-3',
      ],
      elements: [
         {
            id: 'problem-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'problem-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Problem',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'problem-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'Online sunglasses stores often overwhelm users with too many options, unclear navigation, and complicated checkout processes. SunRays aims to simplify browsing and purchasing, helping users find their ideal sunglasses effortlessly.',
               },
            ],
         },
         {
            id: 'goal-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'goal-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'Goal',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'goal-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'The goal of SunRays was to design a modern, responsive e-commerce website that offers a seamless and enjoyable shopping experience, allowing users to easily browse, explore, and purchase sunglasses across desktop and mobile devices.',
               },
            ],
         },
         {
            id: 'role-container',
            classNames: ['p-6', 'bg-neutral-900'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'role-heading',
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.HEADING,
                  text: 'My Role',
                  level: 4,
                  classNames: ['mb-4'],
               },
               {
                  id: 'role-paragraph',
                  type: BLOCK_TYPES.PARAGRAPH,
                  elementType: ELEMENT_TYPES.BLOCK,
                  text: 'This was an individual project where I planned and led each step of the design thinking process, applying my skills in responsive web design.',
               },
            ],
         },
      ],
   },
   responsibilitiesSection: {
      id: 'sunray-responsibilities',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
         'mx-auto',
      ],
      elements: [
         {
            id: 'responsibilities-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Responsibilities',
            level: 4,
         },
         {
            id: 'responsibilities-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Researched common e-commerce UX patterns to identify best practices',
               'Designed user flows for product discovery, detail views, cart, and checkout',
               'Built wireframes, interactive prototypes, and polished high-fidelity mockups in Figma',
               'Applied responsive design principles to ensure consistency across mobile and desktop',
               'Packaged project into a case study for portfolio presentation',
            ],
         },
      ],
   },
   appPreviewSection: {
      id: 'sunray-app-preview',
      classNames: ['w-full', 'mx-auto', 'mt-20'],
      elements: [
         {
            id: 'app-preview-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/sunrayPreview.svg',
            alt: 'SunRay App Preview',
            classNames: ['w-full', 'h-auto', 'object-cover'],
            loading: IMAGE_LOADING.LAZY,
         },
      ],
   },
   userResearchSection: {
      id: 'sunray-user-research',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'mx-auto',
         'w-full',
         'max-w-screen-md',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-research-block-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Research',
            level: 4,
         },
         {
            id: 'user-research-block-paragraph1',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'To understand user behavior and expectations, I conducted qualitative research combining:',
         },
         {
            id: 'user-research-list',
            classNames: ['pl-6'],
            type: BLOCK_TYPES.LIST,
            elementType: ELEMENT_TYPES.BLOCK,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Secondary Research: Analyzing competitor websites',
               'Informal Interviews: Speaking with potential users about their online shopping habits',
            ],
         },
         {
            id: 'user-research-block-paragraph2',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The goal was  to uncover shopping behaviors, pain points, and preferences in online eyewear shopping.',
         },
      ],
   },
   userResearchKeyInsightsSection: {
      id: 'sunray-user-research-key-insights',
      classNames: ['flex', 'flex-col', 'space-y-6', 'mt-20'],
      elements: [
         {
            id: 'user-research-key-insights-block-heading',
            classNames: ['w-full', 'max-w-screen-md', 'mx-auto', 'px-4', 'sm:px-8', 'md:px-12'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Research -  Key Insights',
            level: 4,
         },
         {
            id: 'user-research-key-insights-cards',
            classNames: [
               'w-full',
               'max-w-screen-xl',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
               'gap-6',
               'grid',
               'grid-cols-1',
               'md:grid-cols-2',
               'lg:grid-cols-4',
            ],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'overwhelming-navigation-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'overwhelming-navigation-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/sunrayNumberOne.svg',
                        alt: 'Overwhelming Navigation',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'overwhelming-navigation-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Overwhelming Navigation',
                     },
                     {
                        id: 'overwhelming-navigation-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users found it difficult to quickly locate products due to cluttered or unclear navigation.',
                     },
                  ],
               },
               {
                  id: 'limited-product-information-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'limited-product-information-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/sunrayNumberTwo.svg',
                        alt: 'Limited Product Information',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'limited-product-information-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Limited Product Information',
                     },
                     {
                        id: 'limited-product-information-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Lack of detailed product descriptions, leaving users uncertain about frame materials, lens quality etc.',
                     },
                  ],
               },
               {
                  id: 'complicated-checkout-process-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'complicated-checkout-process-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/sunrayNumberThree.svg',
                        alt: 'Complicated Checkout Process',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'complicated-checkout-process-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Complicated Checkout Process',
                     },
                     {
                        id: 'complicated-checkout-process-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'A long and multi-step checkout discouraged users, often leading to cart abandonment.',
                     },
                  ],
               },
               {
                  id: 'lack-of-mobile-optimization-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'lack-of-mobile-optimization-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/sunrayNumberFour.svg',
                        alt: 'Lack of Mobile Optimization',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'lack-of-mobile-optimization-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Lack of Mobile Optimization',
                     },
                     {
                        id: 'personalized-suggestions-boost-enjoyment-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'On smaller screens, users struggled with poor layouts and slow performance, making browsing and purchasing frustrating.',
                     },
                  ],
               },
            ],
         },
      ],
   },
   personaSection: {
      id: 'sunray-persona',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'persona-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Persona',
            level: 4,
         },
         {
            id: 'persona-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Based on my research, I created a persona to represent the target customers of SunRays—individuals who value both style and convenience when shopping for sunglasses online. This persona captures their goals, frustrations, and behaviors, serving as a reference point to guide design decisions and ensure the website addresses real user needs.',
         },
         {
            id: 'persona-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/sunrayPersona.svg',
            alt: 'SunRay Persona Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   problemStatementSection: {
      id: 'sunray-problem-statement',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'problem-statement-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Problem Statement',
            level: 4,
         },
         {
            id: 'problem-statement-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Emma is a 28-year-old digital marketing specialist who needs a quick and seamless way to shop for stylish sunglasses online because she often shops during short breaks and gets frustrated with cluttered websites and long checkouts.',
         },
      ],
   },
   userFlowSection: {
      id: 'sunray-user-flow',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-flow-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'User Flow',
            level: 4,
         },
         {
            id: 'user-flow-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The user flow illustrates the step-by-step journey a customer takes on SunRays, from landing on the site to completing a purchase. Mapping out this flow helped me identify key touchpoints, reduce friction in navigation, and ensure a smooth, intuitive shopping experience across both desktop and mobile.',
         },
         {
            id: 'user-flow-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/sunrayUserFlow.svg',
            alt: 'SunRay User Flow Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   siteMapSection: {
      id: 'sunray-site-map',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'user-flow-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Site Map',
            level: 4,
         },
         {
            id: 'user-flow-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'I built user-focused flows to ensure that my personas could successfully complete their key objectives while reducing any existing pain points.',
         },
         {
            id: 'site-map-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/sunraySiteMap.svg',
            alt: 'SunRay Site Map Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   paperWireframesSection: {
      id: 'sunray-paper-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'paper-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Paper Wireframes',
            level: 4,
         },
         {
            id: 'paper-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Focusing on the core features identified during user research, I sketched the first wireframes using pen and paper. ',
         },
         {
            id: 'paper-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotPaperWireframes.svg',
            alt: 'SunRay Paper Wireframes Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   digitalWireframesSection: {
      id: 'sunray-digital-wireframes',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'digital-wireframes-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Digital Wireframes',
            level: 4,
         },
         {
            id: 'digital-wireframes-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Based on research insights and initial sketches, I created digital wireframes in Figma to define the layout and structure of the SunRays website, focusing on a seamless shopping flow, clear hierarchy, and responsive design.',
         },
         {
            id: 'digital-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/sunrayDigitalWireframe1.svg',
            alt: 'SunRay Digital Wireframes Image 1',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
         {
            id: 'digital-wireframes-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/sunrayDigitalWireframe2.svg',
            alt: 'SunRay Digital Wireframes Image 2',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   lowFidelityPrototypeSection: {
      id: 'sunray-low-fidelity-prototype',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'low-fidelity-prototype-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Low-Fidelity Prototype',
            level: 4,
         },
         {
            id: 'low-fidelity-prototype-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'I created a low-fidelity prototype from the user flow diagram and wireframes to test functionality before incorporating it into the final design and ensure accessibility for end-users.',
         },
         {
            id: 'low-fidelity-prototype-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/sunrayLowFidelityPrototype.svg',
            alt: 'SunRay Low-Fidelity Prototype Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   usabilityStudySection: {
      id: 'sunray-usability-study',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'usability-study-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Usability Study',
            level: 4,
         },
         {
            id: 'usability-study-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'To evaluate the design and enhance the user experience, I conducted an unmoderated usability test with a small group of participants. The goal was to observe how users browsed products, added items to the cart, and completed checkout, focusing on clarity, ease of navigation, and overall satisfaction.',
         },
      ],
   },
   usabilityStudyFindingsSection: {
      id: 'sunray-usability-study-findings',
      classNames: ['flex', 'flex-col', 'space-y-6', 'mt-20'],
      elements: [
         {
            id: 'usability-study-findings-heading',
            classNames: ['w-full', 'max-w-screen-md', 'mx-auto', 'px-4', 'sm:px-8', 'md:px-12'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Usability Study - Findings',
            level: 4,
         },
         {
            id: 'usability-study-findings-cards',
            classNames: [
               'w-full',
               'max-w-screen-lg',
               'mx-auto',
               'px-4',
               'sm:px-8',
               'md:px-12',
               'gap-6',
               'grid',
               'grid-cols-1',
               'md:grid-cols-3',
            ],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'quick-checkout-options-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'quick-checkout-options-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/sunrayNumberOne.svg',
                        alt: 'Quick Checkout Options',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'quick-checkout-options-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Quick Checkout Options',
                     },
                     {
                        id: 'quick-checkout-options-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users expressed the need for faster and more convenient checkout options to complete their purchases easily.',
                     },
                  ],
               },
               {
                  id: 'customer-reviews-visibility-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'customer-reviews-visibility-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/sunrayNumberTwo.svg',
                        alt: 'Customer Reviews Visibility',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'customer-reviews-visibility-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Customer Reviews Visibility',
                     },
                     {
                        id: 'customer-reviews-visibility-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Users expected to see review counts (e.g., ★★★★☆ 71 Reviews) directly near the product title. Placing this information only in additional tabs made it less discoverable',
                     },
                  ],
               },
               {
                  id: 'cart-feedback-indicator-container',
                  classNames: [
                     'flex',
                     'flex-col',
                     'space-y-3',
                     'items-center',
                     'p-6',
                     'bg-neutral-900',
                  ],
                  elementType: ELEMENT_TYPES.CONTAINER,
                  elements: [
                     {
                        id: 'cart-feedback-indicator-image',
                        elementType: ELEMENT_TYPES.BLOCK,
                        type: BLOCK_TYPES.IMAGE,
                        src: '/src/assets/images/sunrayNumberThree.svg',
                        alt: 'Cart Feedback Indicator',
                        width: 48,
                        height: 48,
                     },
                     {
                        id: 'cart-feedback-indicator-paragraph-bold',
                        classNames: ['font-bold', 'text-xl', 'text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'Cart Feedback Indicator',
                     },
                     {
                        id: 'cart-feedback-indicator-paragraph',
                        classNames: ['text-center'],
                        type: BLOCK_TYPES.PARAGRAPH,
                        elementType: ELEMENT_TYPES.BLOCK,
                        text: 'The cart icon did not display the number of added items, which confused users and made it difficult to confirm successful additions.',
                     },
                  ],
               },
            ],
         },
      ],
   },
   designRefinementsSection: {
      id: 'sunray-design-refinements',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'design-refinements-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Design Refinements',
            level: 4,
         },
         {
            id: 'design-refinements-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Based on feedback:',
         },
         {
            id: 'design-refinements-list',
            classNames: ['pl-6'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.LIST,
            listType: LIST_TYPES.UNORDERED,
            markerStyle: LIST_MARKERS.DISC,
            items: [
               'Highlighted quick checkout options for faster purchasing',
               'Review details were displayed directly under product titles',
               'Added cart item counter to the top navigation',
            ],
         },
         {
            id: 'design-refinements-image1',
            classNames: ['grid', 'grid-cols-1', 'md:grid-cols-2', 'gap-6'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'design-refinement-image1',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.IMAGE,
                  src: '/src/assets/images/sunrayDesignRefinement1.svg',
                  alt: 'Design Refinement 1',
               },
               {
                  id: 'design-refinement-image2',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
                  elementType: ELEMENT_TYPES.BLOCK,
                  type: BLOCK_TYPES.IMAGE,
                  src: '/src/assets/images/sunrayDesignRefinement2.svg',
                  alt: 'Design Refinement 2',
               },
            ],
         },
      ],
   },
   finalDesignSection: {
      id: 'sunray-final-design',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'pb-6',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'final-design-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Final Design',
            level: 4,
         },
         {
            id: 'final-design-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Below are the final high-fidelity screens designed for both desktop and mobile versions of SunRays, showcasing the responsive user experience and visual consistency across devices.',
         },
      ],
   },
   finalDesignMobileImagesSection: {
      id: 'sunray-final-design-mobile-images',
      classNames: ['w-full', 'py-10', 'px-4', 'sm:px-8', 'md:px-40', 'bg-neutral-900'],
      elements: [
         {
            id: 'final-design-mobile-heading',
            classNames: ['mb-10'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Mobile Screens',
            level: 4,
         },
         {
            id: 'final-design-mobile-image-container',
            classNames: [
               'w-full',
               'grid',
               'grid-cols-1',
               'md:grid-cols-2',
               'lg:grid-cols-4',
               'gap-15',
            ],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'final-design-image-1',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign1.svg',
                  alt: 'SunRay Final Design Image 1',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-image-2',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign2.svg',
                  alt: 'SunRay Final Design Image 2',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-image-3',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign3.svg',
                  alt: 'SunRay Final Design Image 3',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-image-4',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign4.svg',
                  alt: 'SunRay Final Design Image 4',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-image-5',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign5.svg',
                  alt: 'SunRay Final Design Image 5',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-image-6',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign6.svg',
                  alt: 'SunRay Final Design Image 6',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-image-7',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign7.svg',
                  alt: 'SunRay Final Design Image 7',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-image-8',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesign8.svg',
                  alt: 'SunRay Final Design Image 8',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
            ],
         },
      ],
   },
   finalDesignDesktopImagesSection: {
      id: 'sunray-final-design-desktop-images',
      classNames: ['w-full', 'py-10', 'px-4', 'sm:px-8', 'md:px-40', 'bg-neutral-900', 'mt-20'],
      elements: [
         {
            id: 'final-design-desktop-heading',
            classNames: ['mb-10'],
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Desktop Screens',
            level: 4,
         },
         {
            id: 'final-design-desktop-image-container',
            classNames: ['w-full', 'grid', 'grid-cols-1', 'md:grid-cols-2', 'gap-15'],
            elementType: ELEMENT_TYPES.CONTAINER,
            elements: [
               {
                  id: 'final-design-desktop-image-1',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign1.svg',
                  alt: 'SunRay Final Design Desktop Image 1',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-desktop-image-2',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign2.svg',
                  alt: 'SunRay Final Design Desktop Image 2',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-desktop-image-3',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign3.svg',
                  alt: 'SunRay Final Design Desktop Image 3',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-desktop-image-4',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign4.svg',
                  alt: 'SunRay Final Design Desktop Image 4',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-desktop-image-5',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign5.svg',
                  alt: 'SunRay Final Design Desktop Image 5',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-desktop-image-6',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign6.svg',
                  alt: 'SunRay Final Design Desktop Image 6',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-desktop-image-7',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign7.svg',
                  alt: 'SunRay Final Design Desktop Image 7',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
               {
                  id: 'final-design-desktop-image-8',
                  type: BLOCK_TYPES.IMAGE,
                  elementType: ELEMENT_TYPES.BLOCK,
                  src: '/src/assets/images/sunrayFinalDesktopDesign8.svg',
                  alt: 'SunRay Final Design Desktop Image 8',
                  classNames: ['w-full', 'h-auto', 'object-cover'],
               },
            ],
         },
      ],
   },
   highFidelityPrototypeSection: {
      id: 'sunray-high-fidelity-prototype',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'pt-10',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'high-fidelity-prototype-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'High-Fidelity Prototype',
            level: 4,
         },
         {
            id: 'high-fidelity-prototype-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'The high-fidelity prototype showcases the final visuals and interactions providing a realistic view of the SunRays shopping experience.',
         },
         {
            id: 'high-fidelity-prototype-image',
            type: BLOCK_TYPES.IMAGE,
            elementType: ELEMENT_TYPES.BLOCK,
            src: '/src/assets/images/beatSpotHighFidelityPrototype.svg',
            alt: 'SunRay High-Fidelity Prototype Image',
            classNames: ['w-full', 'h-auto', 'object-cover'],
         },
      ],
   },
   finalOutcomeAndLearningsSection: {
      id: 'sunray-final-outcome-and-learnings',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'final-outcome-and-learnings-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Final Outcome and Learnings',
            level: 4,
         },
         {
            id: 'final-outcome-and-learnings-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'Designing SunRays was an exciting journey in crafting a modern, fashion-forward e-commerce experience. Iterating through research, wireframes, and usability testing helped me refine every detail — from product discovery to checkout. This project strengthened my skills in responsive web design and reinforced the importance of balancing aesthetics with usability.',
         },
      ],
   },
   closingReflectionSection: {
      id: 'sunray-closing-reflection',
      classNames: [
         'flex',
         'flex-col',
         'space-y-6',
         'mt-20',
         'mb-30',
         'w-full',
         'max-w-screen-md',
         'mx-auto',
         'px-4',
         'sm:px-8',
         'md:px-12',
      ],
      elements: [
         {
            id: 'closing-reflection-heading',
            elementType: ELEMENT_TYPES.BLOCK,
            type: BLOCK_TYPES.HEADING,
            text: 'Closing Reflection',
            level: 4,
         },
         {
            id: 'closing-reflection-paragraph',
            type: BLOCK_TYPES.PARAGRAPH,
            elementType: ELEMENT_TYPES.BLOCK,
            text: 'SunRays allowed me to explore the full design process while focusing on creating a seamless shopping experience. Small refinements, guided by research and testing, made a significant difference in usability, resulting in a product that is both stylish and user-friendly.',
         },
      ],
   },
};
